import home from "./home.jpg";
import rankUp from "./rank_up.png";
import rankDown from "./rank_down.png";
import stay from "./stay.png";
import bronze from "./bronze.png";
import silver from "./silver.png";
import copper from "./copper.png";
import diamond from "./diamond.png";
import master from "./master.png";
import grandmaster from "./grandmaster.png";

export const homeImage = home;
export const rankUpImage = rankUp;
export const rankDownImage = rankDown;
export const stayImage = stay;
export const bronzeImage = bronze;
export const silverImage = silver;
export const copperImage = copper;
export const diamondImage = diamond;
export const masterImage = master;
export const grandmasterImage = grandmaster;
